### ISSUE TITLE
[Feature Request] Hotkey for switching between normal and changed speed

### ISSUE THREAD

**Issue by boarder2** [polywock/globalSpeed#13]
It'd be great to have a hot key that allowed toggling between 1x speed and whatever the last rate you left off at.

Thanks for the great extension!

**Comment by polywock** [comment]
Seems straightforward enough. I'll include it in the version 3 release. Thanks for the suggestion.

**Comment by NayamAmarshe** [comment]
Is this feature available yet?

**Comment by polywock** [comment]
The version 3 update took longer than anticipated. I'm mostly finished, but still need to do some testing (it was a big refactor). It'll probably get published in a week or so.

**Comment by polywock** [comment]
@NayamAmarshe, @boarder2 . Sorry for the long wait. I've published the update. It should go live in a few days. The S key should now toggle between the set speed (1.0x by default) and the last speed.

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe, @boarder2 . Sorry for the long wait. I've published the update. It should go live in a few days. The S key should now toggle between the set speed (1.0x by default) and the last speed.

Thanks! The new version is pretty good. Love the pop sound on key press.

**Comment by boarder2** [comment]
Awesome! I'm guessing it takes a little more time to publish to the MS Edge store than Chrome? Still shows 2.5.9 there

**Comment by polywock** [comment]
@boarder2 Yeah, still being reviewed. It takes around 3-4 days on average. It used to take just as a long for the Chrome Web Store. But, the latest publish only took an hour. Maybe they improved their review process.
