### ISSUE TITLE
Second "fake" video and speed changing doesn't work 

### ISSUE THREAD

**Issue by QIvan** [polywock/globalSpeed#305]
Hi! Thank you very much for this plugin, it saves me a lot of time! 

I noticed recently a second video track shows up when I watch youtube. 
It looks like this  
![image](https://user-images.githubusercontent.com/782389/208293312-eaf0f924-c2f4-4c94-9d95-41fab97c95b5.png)

and unfortunately, after ~15 seconds after a video has been loaded speed hotkeys stop working =( 

I use Chrome Version 108.0.5359.98 (Official Build) (64-bit)
presumably, the latest version of the plugin (I didn't find where I can check the version number, but I re-installed the plugin before I created this issue. the problem remains) 

It used to work fine about a week ago, so I guess it showed up after an update to either chrome or the plugin itself. 

thank you!

**Comment by didischr** [comment]
same here, for a few days now (perhaps 2 days already)

**Comment by lasmala1000** [comment]
Hello, the same for me...

**Comment by brizone1** [comment]
Doing same for me on Brave v1.46.144 (Dec 14, 2022), and speed control isn't working.  This problem started yesterday (Dec 17), or maybe the evening before for me.

**Comment by polywock** [comment]
Hello. The 2.9.991 update had a bug. The issue should be fixed in the 2.9.992 update, but it's taking a few days to get reviewed by the Chrome Web Store. It should be approved by tomorrow (hopefully), but for now, you can manually load the fixed version. 

[packed.zip](https://github.com/polywock/globalSpeed/files/10251706/packed.zip)

1. Download packed.zip and extract the folder. 
2. open extensions page, chrome://extensions 
3. Disable the original Global Speed. 
4. Enable dev mode in top right of page. 
5. Click "load unpacked" in top left of page and load the folder.

**Comment by polywock** [comment]
An update. Version 2.9.992 got approved. If you haven't received it yet. Make sure to press the update button in the Chrome extensions page. 

Also, if you manually loaded it. You can uninstall that version and re-enable the official one.

**Comment by sangpham2710** [comment]
2.9.992 is updated on my computer but it still doesn't fix it

**Comment by QIvan** [comment]
sorry, I didn't write my feedback. 
Thank you! I reinstalled the plugin and now it works just fine. 
there is still the problem that I see 2 progress bars like on the screen above, but it doesn't affect the main plugin function. 
Thank you for the fix and for the plugin itself, it's really awesome!

**Comment by polywock** [comment]
Youtube has like 4 sound effects preloaded in the background. 

https://www.youtube.com/s/search/audio/failure.mp3
https://www.youtube.com/s/search/audio/no_input.mp3
https://www.youtube.com/s/search/audio/open.mp3
https://www.youtube.com/s/search/audio/success.mp3

The second "fake" one you see is on of these sounds. Global speed hides the ones less than half a second long. Only one of them is long enough to show.

**Comment by QIvan** [comment]
The more you know! 
Thank you for your explanation. 

Happy new year everyone! 
Keep safe.

**Comment by polywock** [comment]
You too, thanks!
