### ISSUE TITLE
Incomplete display of numbers on Firefox browser

### ISSUE THREAD

**Issue by meihus** [polywock/globalSpeed#321]
![image](https://user-images.githubusercontent.com/63285959/213072496-567cf621-7bb6-4865-aecf-f83191ed07fc.png)

**Comment by polywock** [comment]
Hello. Pinning to tool bar seems to fix the issue. In the next update I will just show a single decimal point `1.0` instead of `1.00` so should be solved indirectly.

**Comment by meihus** [comment]
> Hello. Pinning to tool bar seems to fix the issue. In the next update, I planned to just show a single decimal point `1.0` instead of `1.00` so this issue should be solved indirectly.

![image](https://user-images.githubusercontent.com/63285959/214875786-8b9e46dc-134b-4ae7-a6fe-45f9733b0c2f.png)
Hello, after fixing it still shows incomplete, looking forward to your next update.

**Comment by polywock** [comment]
Hello. Apologies for the late reply. Going through the old issues one by one. As of now, the Issue should be fixed on Firefox as Global Speed now only shows a single decimal digit.
